name: Java CI

on:
    push:
        branches: [$default-branch, 'dev']
    pull_request:
        branches: [$default-branch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v2

            - name: setup jdk
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: get keycloak version
              run: echo "KEYCLOAK_VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/jboss/keycloak/tags | jq .results[].name -r | grep -Evi 'beta|test|nightly|latest' | sort -nr | head -n 1)" >> $GITHUB_ENV

            - name: get plugin version
              run: echo "PLUGIN_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

            - name: cache maven
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ env.KEYCLOAK_VERSION }}
                  restore-keys: ${{ runner.os }}-m2

            - name: build
              run: mvn --batch-mode --update-snapshots verify

            - name: archive jar
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: target/*.jar

    publish:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ github.ref == 'refs/heads/dev' }}
        steps:
            - name: check version
              run: echo "$KEYCLOAK_VERSION $KEYCLOAK_VERSION"
